
function(set_library_prefix_and_suffix USE_DYNAMIC_VAR PREFIX_VAR_NAME SUFFIX_VAR_NAME)

  if (${USE_DYNAMIC_VAR})
      set(${SUFFIX_VAR_NAME} ${CMAKE_SHARED_LIBRARY_SUFFIX} PARENT_SCOPE)
      set(${PREFIX_VAR_NAME} ${CMAKE_SHARED_LIBRARY_PREFIX} PARENT_SCOPE)
  else()
      set(${SUFFIX_VAR_NAME} ${CMAKE_STATIC_LIBRARY_SUFFIX} PARENT_SCOPE)
      set(${PREFIX_VAR_NAME} ${CMAKE_STATIC_LIBRARY_PREFIX} PARENT_SCOPE)
  endif()

endfunction()


